parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    VendorHousehold\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    VendorHousehold\Repository\UserRepository:
        tags: ['doctrine.repository_service']

    Redis:
        class: Redis
        calls:
            - method: connect
              arguments:
                  - 'redis'
                  - 6379
    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@Redis'
            - prefix: fs-session_
